# Language setting
language: python

# Version number
python:
  - 2.7

build:
  pre_ci_boot:
    image_name: drydock/u14pytall
    image_tag: master
    pull: true
    options: '--privileged=true --net=bridge'
  ci:
    - python --version
 
resources:
#cliconfig resources to verify account integration 
  - name: cli_awsKeys
    type: cliConfig
    integration: ghOrgAccIntAwsKeys
    
  - name: cli_dockerRegistry
    type: cliConfig
    integration: ghOrgAccIntDockerRegistry
    
  - name: cli_gcl
    type: cliConfig
    integration: ghOrgAccIntGoogleCloud
    
  - name: cli_jfrog
    type: cliConfig
    integration: ghOrgAccIntJfrogArtifactory
  
  - name: cli_kubernetes
    type: cliConfig
    integration: ghOrgAccIntKubernetes
    
  - name: cli_quay
    type: cliConfig
    integration: ghOrgAccIntQuay

jobs:
# job that checks all the account integrations 
  - name: test_accIntegration_run
    type: runSh
    steps:
    #  - IN: cli_awsKeys
      #- IN: cli_awsKeys
      #  scope:
     #     - ecr
      - IN: cli_dockerRegistry
    #  - IN: cli_gcl
     # - IN: cli_gcl
     #   scope:
     #     - gcr
     # - IN: cli_gcl
     #   scope:
     #     - gke
     # - IN: cli_jfrog
     # - IN: cli_kubernetes
     # - IN: cli_quay
      - TASK:        
      #  - script: echo CLI_AWSKEYS_INTEGRATION_ACCESSKEY=$CLI_AWSKEYS_INTEGRATION_ACCESSKEY
       # - script: echo CLI_AWSKEYS_INTEGRATION_SECRETKEY=${#CLI_AWSKEYS_INTEGRATION_SECRETKEY}
       # - script: echo CLI_AWSKEYS_NAME=$CLI_AWSKEYS_NAME
       # - script: echo CLI_AWSKEYS_ID=$CLI_AWSKEYS_ID
      #  - script: echo CLI_AWSKEYS_TYPE=$CLI_AWSKEYS_TYPE
      #  - script: echo CLI_AWSKEYS_INTEGRATION_TYPE=$CLI_AWSKEYS_INTEGRATION_TYPE
       # - script: echo CLI_AWSKEYS_OPEARATION=$CLI_AWSKEYS_OPERATION
       # - script: echo CLI_AWSKEYS_PATH=$CLI_AWSKEYS_PATH
       # - script: echo CLI_AWSKEYS_POINTER_REGION=$CLI_AWSKEYS_POINTER_REGION
       # - script: echo CLI_AWSKEYS_POINTER_CLUSTERNAME=$CLI_AWSKEYS_POINTER_CLUSTERNAME
       # - script: echo CLI_AWSKEYS_VERSIONNUMBER=$CLI_AWSKEYS_VERSIONNUMBER
       # - script: echo CLI_AWSKEYS_VERSIONNAME=$CLI_AWSKEYS_VERSIONNAME
       # - script: echo CLI_AWSKEYS_VERSIONID=$CLI_AWSKEYS_VERSIONID
     #   - script: docker pull 742038439709.dkr.ecr.us-west-2.amazonaws.com/sample_node
       
        - script: docker pull shippabledocker/sample_node_pvt:ecr
        - script: echo CLI_DOCKER_INTEGRATION_URL=$CLI_DOCKER_INTEGRATION_URL
        - script: echo CLI_DOCKER_INTEGRATION_USERNAME=$CLI_DOCKER_INTEGRATION_USERNAME
        - script: echo CLI_DOCKER_INTEGRATION_PASSWORD=${#CLI_DOCKER_INTEGRATION_PASSWORD}
        - script: echo CLI_DOCKER_INTEGRATION_EMAIL=$CLI_DOCKER_INTEGRATION_EMAIL
        
      #  - script: echo CLI_GCL_INTEGRATION_JSON_KEY=${#CLI_GCL_INTEGRATION_JSON_KEY}
      #  - script: docker pull gcr.io/vidya-project/node1-img:master.33
     
      #  - script: echo CLI_JFROG_INTEGRATION_URL=$CLI_JFROG_INTEGRATION_URL
      #  - script: echo CLI_JFROG_INTEGRATION_USERNAME=$CLI_JFROG_INTEGRATION_USERNAME
      #  - script: echo CLI_JFROG_INTEGRATION_PASSWORD=${#CLI_JFROG_INTEGRATION_PASSWORD}
      #  - script: jfrog rt dl test-jfrog-ship/testoct.sh
       
       # - script: echo CLI_KUBERNETES_INTEGRATION_KUBECONFIGCONTENT=${#CLICONFIGKUBERNETES_INTEGRATION_KUBECONFIGCONTENT}
       # - script: kubectl version
       
       # - script: echo CLI_QUAY_INTEGRATION_ACCESSTOKEN=${#CLI_QUAY_INTEGRATION_ACCESSTOKEN}
       # - script: echo CLI_QUAY_INTEGRATION_USERNAME=$CLI_QUAY_INTEGRATION_USERNAME
       # - script: echo CLI_QUAY_INTEGRATION_PASSWORD=${#CLI_QUAY_INTEGRATION_PASSWORD}
       # - script: echo CLI_QUAY_INTEGRATION_EMAIL=$CLI_QUAY_INTEGRATION_EMAIL
       # - script: docker pull quay.io/revathird/samplenode_test
